In [1]:
# Create the data.
from numpy import pi, sin, cos, mgrid
dphi, dtheta = pi/250.0, pi/250.0
[phi,theta] = mgrid[0:pi+dphi*1.5:dphi,0:2*pi+dtheta*1.5:dtheta]
m0 = 4; m1 = 3; m2 = 2; m3 = 3; m4 = 6; m5 = 2; m6 = 6; m7 = 4;
r = sin(m0*phi)**m1 + cos(m2*phi)**m3 + sin(m4*theta)**m5 + cos(m6*theta)**m7
x = r*sin(phi)*cos(theta)
y = r*cos(phi)
z = r*sin(phi)*sin(theta)

# View it.
from mayavi import mlab
s = mlab.mesh(x, y, z)
mlab.show()

In [3]:
import numpy as np
from mayavi.mlab import *
from mayavi import mlab

pi = np.pi
cos = np.cos
sin = np.sin
dphi, dtheta = pi / 250.0, pi / 250.0
[phi, theta] = np.mgrid[0:pi + dphi * 1.5:dphi,
                            0:2 * pi + dtheta * 1.5:dtheta]
m0 = 4
m1 = 3
m2 = 2
m3 = 3
m4 = 6
m5 = 2
m6 = 6
m7 = 4
r = sin(m0 * phi) ** m1 + cos(m2 * phi) ** m3 + \
        sin(m4 * theta) ** m5 + cos(m6 * theta) ** m7
x = r * sin(phi) * cos(theta)
y = r * cos(phi)
z = r * sin(phi) * sin(theta)
s = mlab.mesh(x, y, z)
mlab.show()

In [2]:
import numpy as np
from mayavi.mlab import *
from mayavi import mlab

n_mer, n_long = 6, 11
dphi = np.pi / 1000.0
phi = np.arange(0.0, 2 * np.pi + 0.5 * dphi, dphi)
mu = phi * n_mer
x = np.cos(mu) * (1 + np.cos(n_long * mu / n_mer) * 0.5)
y = np.sin(mu) * (1 + np.cos(n_long * mu / n_mer) * 0.5)
z = np.sin(n_long * mu / n_mer) * 0.5

l = plot3d(x, y, z, np.sin(mu), tube_radius=0.025, colormap='Spectral')

In [1]:
a = [0:3:1,0:3:1]
a

SyntaxError: invalid syntax (857202059.py, line 1)

In [10]:
import numpy as np

x, y = np.mgrid[0:3:1.5,0:3:1]
print(x)
print(y)

[[0.  0.  0. ]
 [1.5 1.5 1.5]]
[[0. 1. 2.]
 [0. 1. 2.]]


In [1]:
from numpy import sin, cos, mgrid, pi, sqrt
from mayavi import mlab

mlab.figure(fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))
u, v = mgrid[- 0.035:pi:0.01, - 0.035:pi:0.01]

X = 2 / 3. * (cos(u) * cos(2 * v)
        + sqrt(2) * sin(u) * cos(v)) * cos(u) / (sqrt(2) -
                                                 sin(2 * u) * sin(3 * v))
Y = 2 / 3. * (cos(u) * sin(2 * v) -
        sqrt(2) * sin(u) * sin(v)) * cos(u) / (sqrt(2)
        - sin(2 * u) * sin(3 * v))
Z = -sqrt(2) * cos(u) * cos(u) / (sqrt(2) - sin(2 * u) * sin(3 * v))
S = sin(u)

mlab.mesh(X, Y, Z, scalars=S, colormap='YlGnBu', )

# Nice view from the front
mlab.view(.0, - 5.0, 4)
mlab.show()

In [1]:
import numpy as np
from numpy import *

from mayavi import mlab

t = np.linspace(0, 2*pi, 50)
u = cos(t)*pi
x, y, z = sin(u), cos(u), sin(t)
mlab.clf()
mlab.plot3d(x, y, z, t)
mlab.show()

In [7]:
import numpy as np
from numpy import *

from mayavi import mlab

phi, theta = np.mgrid[0:2*pi: 200j, 0:2*pi:200j]
x = sin(phi)*cos(theta)
y = sin(phi)*sin(theta)
z = cos(phi)

mlab.clf()
mlab.mesh(x, y, z)
mlab.show()

In [3]:
import numpy as np
from numpy import *

from mayavi import mlab

#x, y, z = [[1,0, 0], [0, 1, 0], [0, 0, 1]]
#t = [[0,1, 2]]

points = np.array([[0, 0, 0], [1, 0, 0], [1, 1, 0], [0, 1, 0], [0, 0, 1],
                   [1, 0, 1], [1, 1, 1], [0, 1, 1], [0.5, 0.5, 2]])
#t = [[0, 1, 2], [0, 2, 3], [4, 5, 6], [4, 6, 7], [0, 1, 8]]
t = [[0, 1, 2], [0, 2, 3]]
#points = np.array([[0,0, 0], [1, 0, 0], [1, 1, 0]])
x, y, z = points.T
mlab.clf()
mlab.triangular_mesh(x, y, z, t)
mlab.show()

In [1]:
import numpy as np
from numpy import *

from mayavi import mlab

x = [0, 1, 1, 0, 0.5]
y = [0, 0, 1, 1, 0.5]
z = [0, 0, 0, 0 , 1]
t = [[0, 1, 4], [1, 2,4], [2, 3, 4], [3, 0, 4]]

mlab.clf()
mlab.triangular_mesh(x, y, z, t)
mlab.show()

In [21]:
import numpy as np
from mayavi import mlab

d = 240 #bán kính trong hình trụ
D = d + 30 # bán kính ngoài hình trụ
h1 = D #chiều cao hình trụ

#--------------Lớp đế--------------------------------
x = np.array([0, 1, 1, 0, 0, 1, 1, 0])*(430*2+D+200)
y = np.array([0, 0, 1, 1, 0, 0, 1, 1])*(430+D+200)
z = np.array([0, 0, 0, 0, -1, -1, -1, -1])*120
t = [[0, 1, 2], [2, 3, 0], 
    [4, 5, 6], [6, 7, 4], 
    [0, 1, 5], [5, 4, 0], 
    [1, 2, 6], [1, 6, 5], 
    [2, 3, 7], [7, 6, 2], 
    [0, 3, 4], [4, 7, 3]]
mlab.triangular_mesh(x, y, z, t, color = "cool")
#----------------Lớp trên---------------------------
theta = np.linspace(0, 2*np.pi, 50)
h = np.linspace(0, h1, 50)
theta, h = np.meshgrid(theta, h)

for i in range(0, 3, 1):
    for r in np.linspace(d/2, D/2, 30):
        x3 = 430*i + D/2 + 100 + (r)*np.cos(theta)
        y3 = D/2 + 100 + (r)*np.sin(theta)
        mlab.mesh(x3, y3, h)
        
for i in range(0, 3, 1):
    for r in np.linspace(d/2, D/2, 30):
        x3 = 430*i + D/2 + 100 + (r)*np.cos(theta)
        y3 = 430 + D/2 + 100 + (r)*np.sin(theta)
        mlab.mesh(x3, y3, h)

mlab.show()

TraitError: The 'color' trait of a SurfaceFactory instance must be a tuple of the form: (0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0, 0.0 <= a floating point number <= 1.0) or None, but a value of 'cool' <class 'str'> was specified.

In [ ]:
import numpy as np
from mayavi import mlab

d = 240 #bán kính trong hình trụ
D = d + 30 # bán kính ngoài hình trụ
h1 = D #chiều cao hình trụ

theta = np.linspace(0, 2*np.pi, h1)
h = np.linspace(0, h1, h1)
theta, h = np.meshgrid(theta, h)

#các điểm trên bề mặt bán kính d
x1 = (d/2)*np.cos(theta)
y1 = (d/2)*np.sin(theta)
mlab.mesh(x1, y1, h)

#các điểm trên bề mặt bán kính ngoài
x2 = (D/2)*np.cos(theta)
y2 = (D/2)*np.sin(theta)
mlab.mesh(x2, y2, h)

#nắp hình trụ
#r = np.linspace(d, D, h1)
#r = np.meshgrid(r)
for r in np.linspace(d, D, h1):
    x3 = 500 + r*np.cos(theta)
    y3 = 500 + r*np.sin(theta)
    mlab.mesh(x3, y3, h)

mlab.show()

In [5]:
import numpy as np
from mayavi import mlab

height = 2.0  # Chiều cao của hình trụ
resolution = 50  # Độ phân giải của mạng lưới
theta = np.linspace(0, 2*np.pi, resolution)
z = np.linspace(0, height, resolution)

inner_radius = 0.5  # Bán kính trong
outer_radius = 1.0  # Bán kính ngoài

theta, z = np.meshgrid(theta, z)

# Tạo các điểm trên bề mặt trong của hình trụ
x_inner = inner_radius * np.cos(theta)
y_inner = inner_radius * np.sin(theta)
mlab.mesh(x_inner, y_inner, z)

# Tạo các điểm trên bề mặt ngoài của hình trụ
x_outer = outer_radius * np.cos(theta)
y_outer = outer_radius * np.sin(theta)
mlab.mesh(x_outer, y_outer, z)

mlab.show()